spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 4cfd499a26e10797eb55e33b7e18188a
            client-secret: Ox1fEFiC0KvrPdMKDPAgWSQ2MWjuYg7S
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
          google:
            client-id: 68173911510-gabsc86hphsf7oc3jsj8tfks361vc8dh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-name: Naver
            client-id: zJOOM7S82s9QO2fMLZve
            client-secret: mrfmsQaDxT
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response