server:
  port: 8080
spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.82.246.171:3306/shoulder
    username: shoulder
    password: '@shoulder!database@'
    hikari:
      connection-test-query: select now()
      maximum-pool-size: 10
mybatis:
  mapper-locations: mybatis/*.xml
  type-aliases-package: me.haeseok.sts.dto,me.haeseok.sts.request


me:
  haeseok:
    sts:
      upload:
        directory:
          moim: /Users/haeseok/Desktop/dev/upload
#          moim: d:/uploads/moim